language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

services:
  - redis-server
  - postgresql

dist: trusty

addons:
  postgresql: "12"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - clang
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

before_install:
  - "psql -c 'create database golang_gin_db;' -U postgres"
  - "psql golang_gin_db -c 'create extension postgis;' -U postgres"
  - "psql -U postgres < ./db/database.sql"
  - sleep 3

install:
  - go mod init
  - go list -m all
  - mv .env_rename_me .env
  - mkdir cert/ && sh generate-certificate.sh

script:
  - go test -v ./tests/*
